flags:
  haskeline:
    brick: true
extra-package-dbs: []
packages:
- '.'
- ../PL
- ../PLGrammar
- ../PLParser
- ../PLPrinter
- ../PLEditor
- ../PLLispy
- ../PLLabel
- location:
    git: https://github.com/rootmos/haskeline.git
    commit: bf8164bc747e299524548417f3e947cbd3d47f68
  extra-dep: true
extra-deps:
- haskeline-0.7.4.0
- megaparsec-6.4.0
- parser-combinators-0.4.0
resolver: lts-9.18
