resolver: lts-14.20
flags:
  haskeline:
    brick: true
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/syallop/PLCore
    commit: dc9b603e4afa54610db14df2bfeeb33ee2808f24
  extra-dep: true
- location:
    git: https://github.com/syallop/PLEditor
    commit: 8f474ec94f444c3da6f4e467231e5cf03761b67e
  extra-dep: true
- location:
    git: https://github.com/syallop/PLLispy
    commit: 2d49df616d675cb61780e11daea66713ddd2568d
  extra-dep: true
- location:
    git: https://github.com/syallop/PLParser
    commit: 7adea4ba5ec67f7fee80f9903595e1ab825e313b
  extra-dep: true
- location:
    git: https://github.com/syallop/PLGrammar
    commit: 8583dfc6b56b88069fee00b9786da6f15f6d4cd0
  extra-dep: true
- location:
    git: https://github.com/syallop/PLPrinter
    commit: 65f4d3805c06fbbe0e4313f17a2129e5fe2187f9
  extra-dep: true
- location:
    git: https://github.com/syallop/Reversible
    commit: 84188a89af962716dc0534d552da715305cb0cf5
  extra-dep: true
- location:
    git: https://github.com/syallop/PLLabel
    commit: 9433cf7963e43b4df06f57939218956c3d2dacc4
  extra-dep: true
- location:
    git: https://github.com/syallop/DSL-Compose.git
    commit: 5a95ae855f3291aa3193a7424892035226b10d2f
  extra-dep: true
- location:
    git: https://github.com/rootmos/haskeline.git
    commit: bf8164bc747e299524548417f3e947cbd3d47f68
  extra-dep: true
extra-deps:
- megaparsec-7.0.4
- parser-combinators-1.0.1
- brick-0.46
- config-ini-0.2.4.0@sha256:38a6d484d471c6fac81445de2eac8c4e8c82760962fca5491ae1c3bfca9c4047
- data-clist-0.1.2.2@sha256:4d70add0a200a178853cd37c6469101bac3c36aebb3aa9c503ff225211b1a8c9
- text-zipper-0.10.1@sha256:8b73a97a3717a17df9b0a722b178950c476ff2268ca5c583e99d010c94af849e
- word-wrap-0.4.1@sha256:f72233b383ef569c557bfd9812cbb8e306c415ce509082c0bd15ee51c0239ccc
allow-newer: true
